[package]
name = "tiny_redis"
version = "0.1.0"
edition = "2021"

[lib]
name = "tiny_redis"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bencher = "0.1.5"

[[bench]]
name = "main"
harness = false